(** Draws the state of each player.

    This module prints the state of each player, including their name,
    properties owned, bank account, and current location, along with their
    visual location on the board before and after each turn. *)

val width : int
(** The width of the window generated by the gui *)

val height : int
(** The heigt of the window generated by the gui *)

val setup : unit -> unit
(** [setup] sets up the initial window *)

val draw_intro : unit -> unit
(** [draw_intro] draws the introduction window *)

val draw_board_base : unit -> unit
(** [draw_board_base] draws the background monopoly board. *)

val center_text : int -> int -> string -> Raylib.Color.t -> unit
(** [center_text line_num total_lines string color] prints [string] in the
    middle of the page with the color [color]. To print longer messages, call
    [center_text] should be called for each line. [line_num] is the line number
    of the message and [total_lines] is the total number of lines in the
    message. *)

val print_insns : string -> Raylib.Color.t -> unit
(** [print_insns insns color] prints the instructions [insns] at the bottom of
    the page, under the board. *)

val print_player_stats : Player.t -> unit
(** [print_stats player] prints the name, balance, position, and properties
    owned of the current player *)

val player_position : Player.t -> Player.t -> unit
(** [player_posiiton player1 player2 color] draws a circle representing the
    players, [player1] and [player2] on the board with their respective colors.
    [player1] is the current player. *)

val draw_player_window : Player.t -> Player.t -> unit
(** [draw_player_window player1 player2] draws the window showing the state of
    the [player1] and the location of [player2]. [player1] is the current
    player. *)

val draw_exit : unit -> unit
(** [draw_exit] draws the exit window, when a player types "Quit" into the
    terminal. *)
